import type { Metadata } from 'next';
import './globals.css';
// import { Providers } from '@/components';
// import { Providers } from '@/components';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('LAYOUT RERENDER');

  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
